version: '3.8'
services:
  nginx:
    image: nginx:latest
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d      
    networks:
      - acme
      - backend
    deploy:
        replicas: 3
        rollback_config:
            parallelism: 0
        update_config:
            parallelism: 1
            delay: 5s
            failure_action: rollback

  docker-gen:
    image: helder/docker-gen:latest
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen=true
    command: -notify "docker-label-sighup com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy" -watch -wait 10s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - ./config/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - acme
      - backend
    deploy:
        update_config:
            delay: 5s
            failure_action: rollback

  acme-companion:
    image: nginxproxy/acme-companion:latest
    environment:
      - DEFAULT_EMAIL=fsu.cs.acm@gmail.com
    volumes:
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs:rw
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - acme 
    deploy:
        update_config:
            delay: 5s
            failure_action: rollback     

volumes:
  acme:
  certs:
  conf:
  html:
  vhost:

networks:
  acme:
      name: acme
  backend:
    name: proxied-apps
