version: '3.8'
services:
    nginx-proxy:
        image: nginxproxy/nginx-proxy:0.9
        ports:
            - 80:80
            - 443:443
        volumes:
            - html:/usr/share/nginx/html
            - vhost:/etc/nginx/vhost.d
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./certs:/etc/nginx/certs:ro
            - ./config/nginx-proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
        networks:
            - backend
        deploy:
            replicas: 2
            rollback_config:
                parallelism: 0
            update_config:
                parallelism: 1
                delay: 5s
                failure_action: rollback
volumes:
    #certs:
    html:
    vhost:
networks:
    backend:
        name: proxied-apps
        